#!/bin/bash

set -o vi
source /opt/fourjs/gst/envgenero

source /opt/ibm/ifxenv.sh
source /opt/oracle_client/oraenv.sh

export JAVA_HOME="$(realpath $(type java|awk '{print $NF}'|sed 's/[()]//g') |sed 's/\/bin\/java$//')"

